import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { useCurrentUser } from '../auth/api/auth-queries';
import { confirmRecord, createRecord, deleteRecord, importRecords, reconcileRecord, updateRecord } from './api';
import { financialRecordKeys, useFinancialRecords, useFinancialRecordTransactions } from './queries';
import type { FinancialRecord, FinancialRecordInput, ImportResult } from './types';

const schema = z.object({ amount: z.coerce.number<number>().positive('Enter an amount greater than zero.'), date: z.string().min(1, 'Select a date.'), category: z.string().trim().min(1, 'Enter a category.'), recurring: z.boolean(), recurringInterval: z.string() });
type Values = z.infer<typeof schema>;
type Resource = 'expenses' | 'revenues';
const money = (amount: number) => new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR' }).format(amount / 100);

function values(record?: FinancialRecord): Values { return { amount: record ? record.amountMinor / 100 : 0, date: record?.date ?? '', category: record?.category ?? '', recurring: record?.recurring ?? false, recurringInterval: record?.recurringInterval ?? '' }; }
function toInput(values: Values, projectId: string): FinancialRecordInput { return { projectId, amountMinor: Math.round(values.amount * 100), date: values.date, category: values.category, recurring: values.recurring, recurringInterval: values.recurring ? values.recurringInterval : undefined }; }

function RecordForm({ resource, projectId, record, onClose }: { resource: Resource; projectId: string; record?: FinancialRecord; onClose: () => void }) {
  const cache = useQueryClient(); const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: values(record) });
  const save = useMutation({ mutationFn: (input: Values) => record ? updateRecord(resource, record, toInput(input, projectId)) : createRecord(resource, toInput(input, projectId)), onSuccess: async () => { await cache.invalidateQueries({ queryKey: financialRecordKeys.records(resource) }); onClose(); } });
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="record-form-title"><div className="modal-head"><h2 id="record-form-title">{record ? `Edit ${resource.slice(0, -1)}` : `Record ${resource.slice(0, -1)}`}</h2></div><form onSubmit={form.handleSubmit(input => save.mutate(input))} noValidate><div className="modal-body form-grid"><div className="form-field"><label htmlFor="record-amount">Amount (EUR)</label><input id="record-amount" type="number" step="0.01" min="0.01" {...form.register('amount')} />{form.formState.errors.amount && <p className="err">{form.formState.errors.amount.message}</p>}</div><div className="form-field"><label htmlFor="record-date">Date</label><input id="record-date" type="date" {...form.register('date')} /></div><div className="form-field full"><label htmlFor="record-category">Category</label><input id="record-category" {...form.register('category')} />{form.formState.errors.category && <p className="err">{form.formState.errors.category.message}</p>}</div><label className="check-row"><input type="checkbox" {...form.register('recurring')} /> Recurring</label>{form.watch('recurring') && <div className="form-field"><label htmlFor="record-interval">Interval</label><select id="record-interval" {...form.register('recurringInterval')}><option value="">Select interval</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></div>}{save.isError && <p className="form-error full" role="alert">We could not save this record.</p>}</div><div className="modal-foot"><button type="button" className="btn" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={save.isPending}>{save.isPending ? 'Saving...' : 'Save'}</button></div></form></section></div>;
}

function ImportDialog({ resource, projectId, onClose }: { resource: Resource; projectId: string; onClose: () => void }) {
  const cache = useQueryClient(); const [file, setFile] = useState<File>(); const [kind, setKind] = useState<'file' | 'document'>('file'); const [result, setResult] = useState<ImportResult>(); const [mapping, setMapping] = useState({ amountColumn: '', dateColumn: '', categoryColumn: '', recurringColumn: '', recurringIntervalColumn: '' });
  const upload = useMutation({ mutationFn: () => file ? importRecords(resource, kind === 'file' ? 'import-file' : 'import-document', file, projectId, kind === 'file' ? { ...mapping, recurringColumn: mapping.recurringColumn || undefined, recurringIntervalColumn: mapping.recurringIntervalColumn || undefined } : undefined) : Promise.reject(new Error('Choose a file.')), onSuccess: async response => { if ('importedCount' in response) setResult(response); else setResult({ importedCount: 1, recordIds: [response.id], skippedRows: [] }); await cache.invalidateQueries({ queryKey: financialRecordKeys.records(resource) }); } });
  return <div className="modal-backdrop"><section className="modal modal-lg" role="dialog" aria-modal="true" aria-labelledby="record-import-title"><div className="modal-head"><h2 id="record-import-title">Import {resource}</h2></div><div className="modal-body">{!result ? <><div className="toolbar"><label><input type="radio" checked={kind === 'file'} onChange={() => setKind('file')} /> CSV / Excel</label><label><input type="radio" checked={kind === 'document'} onChange={() => setKind('document')} /> PDF OCR</label></div><input aria-label="Choose import file" type="file" accept={kind === 'file' ? '.csv,.xlsx,text/csv' : '.pdf,application/pdf'} onChange={event => setFile(event.target.files?.[0])} />{kind === 'file' && <div className="form-grid mt-16">{(['amountColumn', 'dateColumn', 'categoryColumn', 'recurringColumn', 'recurringIntervalColumn'] as const).map(column => <div className="form-field" key={column}><label htmlFor={column}>{column.replace('Column', ' column')}</label><input id={column} value={mapping[column]} onChange={event => setMapping({ ...mapping, [column]: event.target.value })} /></div>)}</div>}{upload.isError && <p className="form-error" role="alert">We could not import this file.</p>}</> : <div role="status"><p className="msg">Import complete: {result.importedCount} records added.</p>{result.skippedRows.length > 0 && <><p>Skipped rows</p><ul>{result.skippedRows.map(row => <li key={row.rowNumber}>Row {row.rowNumber}: {row.reason}</li>)}</ul></>}</div>}</div><div className="modal-foot">{result ? <button className="btn btn-primary" type="button" onClick={onClose}>Done</button> : <><button className="btn" type="button" onClick={onClose}>Cancel</button><button className="btn btn-primary" type="button" disabled={!file || (kind === 'file' && (!mapping.amountColumn || !mapping.dateColumn || !mapping.categoryColumn)) || upload.isPending} onClick={() => upload.mutate()}>{upload.isPending ? 'Importing...' : 'Import'}</button></>}</div></section></div>;
}

function ConfirmDialog({ resource, projectId, record, onClose }: { resource: Resource; projectId: string; record: FinancialRecord; onClose: () => void }) {
  const cache = useQueryClient(); const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: values(record) }); const confirm = useMutation({ mutationFn: (input: Values) => confirmRecord(resource, record, toInput(input, projectId)), onSuccess: async () => { await cache.invalidateQueries({ queryKey: financialRecordKeys.records(resource) }); onClose(); } });
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="confirm-import-title"><div className="modal-head"><h2 id="confirm-import-title">Review imported draft</h2></div><form onSubmit={form.handleSubmit(input => confirm.mutate(input))}><div className="modal-body form-grid"><p className="full">Check the extracted values before this record enters the books.</p><div className="form-field"><label htmlFor="confirm-amount">Amount (EUR)</label><input id="confirm-amount" type="number" step="0.01" {...form.register('amount')} /></div><div className="form-field"><label htmlFor="confirm-date">Date</label><input id="confirm-date" type="date" {...form.register('date')} /></div><div className="form-field full"><label htmlFor="confirm-category">Category</label><input id="confirm-category" {...form.register('category')} /></div></div><div className="modal-foot"><button className="btn" type="button" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={confirm.isPending}>Confirm record</button></div></form></section></div>;
}

export function FinancialRecordsPage({ resource }: { resource: Resource }) {
  const user = useCurrentUser(); const records = useFinancialRecords(resource); const transactions = useFinancialRecordTransactions(resource); const cache = useQueryClient(); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<FinancialRecord>(); const [importOpen, setImportOpen] = useState(false); const [draft, setDraft] = useState<FinancialRecord>();
  const reconcile = useMutation({ mutationFn: ({ record, transactionId }: { record: FinancialRecord; transactionId: string }) => reconcileRecord(resource, record, transactionId), onSuccess: async () => { await cache.invalidateQueries({ queryKey: financialRecordKeys.records(resource) }); await cache.invalidateQueries({ queryKey: financialRecordKeys.transactions(resource) }); } });
  const remove = useMutation({ mutationFn: (record: FinancialRecord) => deleteRecord(resource, record), onSuccess: () => cache.invalidateQueries({ queryKey: financialRecordKeys.records(resource) }) });
  const singular = resource.slice(0, -1); const projectId = user.data?.projectId ?? '';
  return <main className="page"><div className="page-head"><div><p className="eyebrow">Books</p><h1>{resource[0].toUpperCase() + resource.slice(1)}</h1><p className="page-intro">Record, import, and reconcile your {resource}.</p></div><div className="page-head-actions"><button className="btn" type="button" onClick={() => setImportOpen(true)}>Import</button><button className="btn btn-primary" type="button" onClick={() => { setEditing(undefined); setFormOpen(true); }}>Record {singular}</button></div></div><section className="card"><div className="table-wrap"><table><thead><tr><th>Date</th><th>Category</th><th className="num">Amount</th><th>Source</th><th>Reconciliation</th><th><span className="visually-hidden">Actions</span></th></tr></thead><tbody>{records.data?.items.map(record => <tr key={record.id}><td>{record.date}</td><td>{record.category || <em>Needs review</em>}</td><td className="num">{record.amountMinor ? money(record.amountMinor) : '-'}</td><td>{record.confirmedAt ? record.importSource : 'Draft OCR'}</td><td>{record.reconciledTransactionId ? 'Reconciled' : record.confirmedAt ? <select aria-label={`Reconcile ${singular}`} defaultValue="" onChange={event => event.target.value && reconcile.mutate({ record, transactionId: event.target.value })}><option value="">Match transaction</option>{transactions.data?.items.map(transaction => <option key={transaction.transactionId} value={transaction.transactionId}>{transaction.date} · {money(transaction.amountMinor)} {transaction.description ?? ''}</option>)}</select> : 'Confirm first'}</td><td><button className="btn btn-compact" type="button" onClick={() => record.confirmedAt ? (setEditing(record), setFormOpen(true)) : setDraft(record)}>{record.confirmedAt ? 'Edit' : 'Review'}</button> <button className="btn btn-compact" type="button" onClick={() => window.confirm(`Delete this ${singular}?`) && remove.mutate(record)}>Delete</button></td></tr>)}</tbody></table>{records.data?.items.length === 0 && <div className="empty-state">No {resource} recorded yet.</div>}</div></section>{formOpen && <RecordForm resource={resource} projectId={projectId} record={editing} onClose={() => setFormOpen(false)} />}{importOpen && <ImportDialog resource={resource} projectId={projectId} onClose={() => setImportOpen(false)} />}{draft && <ConfirmDialog resource={resource} projectId={projectId} record={draft} onClose={() => setDraft(undefined)} />}</main>;
}
