import type { ReactNode } from "react";
import { useState } from "react";
import { Link, useLocation, useParams } from "react-router-dom";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { downloadInvoiceAttachment, removeInvoiceAttachment, replaceInvoiceAttachment, uploadInvoiceAttachment } from "../api/invoices-api";
import { invoiceKeys, useInvoice } from "../api/invoices-queries";
import type { InvoiceDetail } from "../types";

const money = (amount: number) => new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(amount / 100);
function DetailRow({ label, value }: { label: string; value: ReactNode }) { return <div className="kv-row"><span className="k">{label}</span><span className="v">{value}</span></div>; }
type Attachment = InvoiceDetail["attachments"][number];

export function InvoiceDetailPage() {
  const { invoiceId = "" } = useParams();
  const location = useLocation();
  const invoice = useInvoice(invoiceId);
  const cache = useQueryClient();
  const [showTypeChoice, setShowTypeChoice] = useState(false);
  const [removing, setRemoving] = useState<Attachment | null>(null);
  const refresh = async () => { await cache.invalidateQueries({ queryKey: invoiceKeys.all }); };
  const upload = useMutation({ mutationFn: ({ file, type }: { file: File; type?: "invoice" | "other" }) => uploadInvoiceAttachment(invoiceId, file, type), onSuccess: async () => { setShowTypeChoice(false); await refresh(); } });
  const replace = useMutation({ mutationFn: ({ attachment, file }: { attachment: Attachment; file: File }) => replaceInvoiceAttachment(invoiceId, attachment.attachmentId, attachment.version, file), onSuccess: refresh });
  const remove = useMutation({ mutationFn: (attachment: Attachment) => removeInvoiceAttachment(invoiceId, attachment.attachmentId), onSuccess: async () => { setRemoving(null); await refresh(); } });
  const returnTo = `/invoices${location.search}`;
  if (invoice.isPending) return <main className="page"><p role="status">Loading invoice...</p></main>;
  if (invoice.isError || !invoice.data) return <main className="page"><p role="alert">We could not load this invoice.</p><Link className="btn mt-16" to={returnTo}>Back to invoices</Link></main>;
  const detail = invoice.data;
  const hasInvoiceAttachment = detail.attachments.some((attachment) => attachment.type === "invoice");
  const selectFile = (event: React.ChangeEvent<HTMLInputElement>, type?: "invoice" | "other") => { const file = event.currentTarget.files?.[0]; if (file) upload.mutate({ file, type }); event.currentTarget.value = ""; };
  return <main className="page">
    <div className="page-head"><div><p className="eyebrow">Billing</p><h1>Invoice details</h1><p className="page-intro">{detail.counterpartyName} · {detail.direction} {detail.type}</p></div><div className="row-actions visible-actions">{detail.status === "draft" && <Link className="btn btn-primary" to={`/invoices/${invoiceId}/edit${location.search}`}>Edit draft</Link>}<Link className="btn" to={returnTo}>Back to invoices</Link></div></div>
    <div className="grid grid-2"><section className="card card-pad"><h2 className="section-title">Invoice</h2><div className="kv-list"><DetailRow label="Counterparty" value={detail.counterpartyName} /><DetailRow label="Direction" value={detail.direction} /><DetailRow label="Type" value={detail.type} /><DetailRow label="Status" value={<span className={`badge badge-${detail.status === "paid" ? "green" : detail.status === "overdue" ? "red" : "amber"}`}>{detail.status}</span>} /><DetailRow label="Invoice date" value={detail.date} /><DetailRow label="Due date" value={detail.dueDate} /></div></section><section className="card card-pad"><h2 className="section-title">Amounts</h2><div className="kv-list"><DetailRow label="Net" value={money(detail.netAmountMinor)} /><DetailRow label="VAT" value={money(detail.taxAmountMinor)} /><DetailRow label="Total" value={money(detail.totalAmountMinor)} /></div></section></div>
    <section className="card mt-16"><div className="card-head"><h2>Line items</h2></div><div className="table-wrap"><table><thead><tr><th>Description</th><th className="num">Quantity</th><th className="num">Unit price</th><th className="num">VAT</th><th className="num">Net</th><th className="num">Total</th></tr></thead><tbody>{detail.lines.map(line => <tr key={line.invoiceLineId}><td className="cell-title">{line.description}</td><td className="num">{line.quantity}</td><td className="num">{money(line.unitPriceMinor)}</td><td className="num">{`${line.taxRate * 100}%`}</td><td className="num">{money(line.netAmountMinor)}</td><td className="num">{money(line.totalAmountMinor)}</td></tr>)}</tbody></table></div></section>
    <section className="card mt-16"><div className="card-head"><h2>Payment history</h2></div>{detail.payments.length === 0 ? <div className="card-body"><p className="muted">No payments recorded.</p></div> : <div className="table-wrap"><table><thead><tr><th>Date</th><th>Method</th><th className="num">Amount</th><th>Reconciliation</th></tr></thead><tbody>{detail.payments.map(payment => <tr key={payment.paymentId}><td>{payment.date}</td><td>{payment.paymentMethod}</td><td className="num">{money(payment.amountMinor)}</td><td>{payment.reconciledTransactionId ? "Reconciled" : "Not reconciled"}</td></tr>)}</tbody></table></div>}</section>
    <section className="card mt-16"><div className="card-head"><h2>Attachments</h2></div><div className="card-body"><div className="row-actions visible-actions">{hasInvoiceAttachment ? <label className="btn btn-sm">Upload other attachment<input className="visually-hidden" type="file" accept="application/pdf,image/png,image/jpeg" onChange={(event) => selectFile(event)} /></label> : <button className="btn btn-sm" type="button" onClick={() => setShowTypeChoice(true)}>Upload attachment</button>}</div>{detail.attachments.length === 0 ? <p className="muted">No documents attached.</p> : <ul>{detail.attachments.map((attachment) => <li key={attachment.attachmentId}><strong>{attachment.type === "invoice" ? "Invoice" : "Other"}</strong>: {attachment.fileName} <div className="row-actions visible-actions"><button className="btn btn-sm" type="button" onClick={async () => { const blob = await downloadInvoiceAttachment(invoiceId, attachment.attachmentId); window.open(URL.createObjectURL(blob), "_blank", "noopener"); }}>Open attachment</button><label className="btn btn-sm">Replace attachment<input className="visually-hidden" type="file" accept="application/pdf,image/png,image/jpeg" onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) replace.mutate({ attachment, file }); event.currentTarget.value = ""; }} /></label><button className="btn btn-sm" type="button" onClick={() => setRemoving(attachment)}>Remove attachment</button></div></li>)}</ul>}{(upload.isError || replace.isError) && <p role="alert">The attachment could not be uploaded. Use a PDF, PNG, or JPEG no larger than 10 MB.</p>}</div></section>
    {showTypeChoice && <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="attachment-type-title"><div className="modal-head"><h2 id="attachment-type-title">Choose attachment type</h2></div><div className="modal-body"><p>Classify the document before selecting it.</p><div className="row-actions visible-actions"><label className="btn btn-primary">Invoice<input className="visually-hidden" type="file" accept="application/pdf,image/png,image/jpeg" onChange={(event) => selectFile(event, "invoice")} /></label><label className="btn">Other type of attachment<input className="visually-hidden" type="file" accept="application/pdf,image/png,image/jpeg" onChange={(event) => selectFile(event, "other")} /></label></div></div><div className="modal-foot"><button className="btn" type="button" onClick={() => setShowTypeChoice(false)}>Cancel</button></div></section></div>}
    {removing && <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="remove-attachment-title"><div className="modal-head"><h2 id="remove-attachment-title">Remove attachment?</h2></div><div className="modal-body"><p>{removing.fileName} will be permanently removed.</p></div><div className="modal-foot"><button className="btn" type="button" disabled={remove.isPending} onClick={() => setRemoving(null)}>Cancel</button><button className="btn btn-primary" type="button" disabled={remove.isPending} onClick={() => remove.mutate(removing)}>Remove attachment</button></div></section></div>}
  </main>;
}
