import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { describe, expect, it, vi } from 'vitest';
import type { Invoice, Paged } from '../types';
import { InvoicesPage } from './invoices-page';

const mocks = vi.hoisted(() => ({ getInvoices: vi.fn(), getCounterparties: vi.fn(), getCurrentUser: vi.fn(), createInvoice: vi.fn(), downloadInvoice: vi.fn() }));
vi.mock('../api/invoices-api', () => ({ getInvoices: mocks.getInvoices, getCounterparties: mocks.getCounterparties, createInvoice: mocks.createInvoice, createCounterparty: vi.fn(), changeInvoiceStatus: vi.fn(), downloadInvoice: mocks.downloadInvoice }));
vi.mock('../../auth/api/auth-api', () => ({ getCurrentUser: mocks.getCurrentUser }));

function renderPage(invoices: Paged<Invoice> = { items: [], page: 1, pageSize: 100, totalCount: 0 }) { mocks.getInvoices.mockResolvedValue(invoices); mocks.getCounterparties.mockResolvedValue({ items: [{ counterpartyId: 'counterparty-1', type: 'customer', name: 'Acme SL', status: 'active' }], page: 1, pageSize: 100, totalCount: 1 }); mocks.getCurrentUser.mockResolvedValue({ projectId: 'project-1' }); render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><MemoryRouter><InvoicesPage /></MemoryRouter></QueryClientProvider>); }
describe('InvoicesPage', () => { it('shows calculated VAT and submits the derived minor-unit line', async () => { const user = userEvent.setup(); renderPage(); await user.click(screen.getByRole('button', { name: 'Create invoice' })); await user.selectOptions(await screen.findByLabelText('Counterparty'), 'counterparty-1'); await user.type(screen.getByLabelText('Line description'), 'Consulting'); await user.clear(screen.getByLabelText('Unit price (EUR)')); await user.type(screen.getByLabelText('Unit price (EUR)'), '100'); await user.type(screen.getByLabelText('Invoice date'), '2026-09-09'); await user.type(screen.getByLabelText('Due date'), '2026-10-09'); const totals = screen.getAllByText((_, element) => element?.tagName === 'P' && element.textContent?.includes('Net 100,00') && element.textContent.includes('VAT 21,00') && element.textContent.includes('Total 121,00') || false); expect(totals).toHaveLength(1); await user.click(screen.getByRole('button', { name: 'Create draft' })); expect(mocks.createInvoice).toHaveBeenCalledWith(expect.objectContaining({ lines: [expect.objectContaining({ unitPriceMinor: 10000, taxRate: 0.21 })] })); }); });
describe('InvoicesPage', () => { it('shows calculated VAT and submits the derived minor-unit line', async () => { const user = userEvent.setup(); renderPage(); await user.click(screen.getByRole('button', { name: 'Create invoice' })); await user.selectOptions(await screen.findByLabelText('Counterparty'), 'counterparty-1'); await user.type(screen.getByLabelText('Line description'), 'Consulting'); await user.clear(screen.getByLabelText('Unit price (EUR)')); await user.type(screen.getByLabelText('Unit price (EUR)'), '100'); await user.type(screen.getByLabelText('Invoice date'), '2026-09-09'); await user.type(screen.getByLabelText('Due date'), '2026-10-09'); const totals = screen.getAllByText((_, element) => element?.tagName === 'P' && element.textContent?.includes('Net 100,00') && element.textContent.includes('VAT 21,00') && element.textContent.includes('Total 121,00') || false); expect(totals).toHaveLength(1); await user.click(screen.getByRole('button', { name: 'Create draft' })); expect(mocks.createInvoice).toHaveBeenCalledWith(expect.objectContaining({ lines: [expect.objectContaining({ unitPriceMinor: 10000, taxRate: 0.21 })] })); }); it('opens the generated PDF in a new tab from its accessible document action', async () => { const invoices: Paged<Invoice> = { items: [{ invoiceId: 'invoice-1', counterpartyId: 'counterparty-1', counterpartyName: 'Acme SL', direction: 'outgoing', type: 'service', status: 'issued', netAmountMinor: 10000, taxAmountMinor: 2100, totalAmountMinor: 12100, date: '2026-09-09', dueDate: '2026-10-09', version: 1 }], page: 1, pageSize: 100, totalCount: 1 }; mocks.downloadInvoice.mockResolvedValue(new Blob(['invoice'], { type: 'application/pdf' })); const createObjectUrl = vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:invoice-pdf'); const open = vi.spyOn(window, 'open').mockImplementation(() => null); const user = userEvent.setup(); renderPage(invoices); await user.click(await screen.findByRole('button', { name: 'Open generated invoice PDF' })); expect(mocks.downloadInvoice).toHaveBeenCalledWith('invoice-1'); expect(open).toHaveBeenCalledWith('blob:invoice-pdf', '_blank', 'noopener'); createObjectUrl.mockRestore(); open.mockRestore(); }); });
