<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>119e1ee2-f56f-4e95-b24a-a190acf4e791</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contapop.Experience.Api\Contapop.Experience.Api.csproj" />
    <ProjectReference Include="..\Contapop.Identity.Service\Contapop.Identity.Service.csproj" />
    <ProjectReference Include="..\Contapop.Ledger.Service\Contapop.Ledger.Service.csproj" />
    <ProjectReference Include="..\Contapop.Billing.Service\Contapop.Billing.Service.csproj" />
    <ProjectReference Include="..\Contapop.Reconciliation.Service\Contapop.Reconciliation.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.3" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Dapr" Version="13.5.1-beta.748" />
  </ItemGroup>
</Project>
